services:
  fake-survey-generator-ui:
    ports:
      - "3000:443"
    volumes:
      - ./src/client/ui/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs/localhost-key.pem:/certs/localhost-key.pem:ro
      - ./certs/localhost.pem:/certs/localhost.pem:ro

  fake-survey-generator-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=5001
      - ASPNETCORE_Kestrel__Certificates__Default__Password=${DOCKER_COMPOSE_CERTIFICATE_PASSWORD}
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/root/.aspnet/https/FakeSurveyGenerator.API.pfx
      - ConnectionStrings__SurveyContext=Server=sql-server;Database=FakeSurveyGenerator;user id=SA;pwd=<YourStrong!Passw0rd>;Encrypt=false
      - REDIS_PASSWORD=testing
      - REDIS_SSL=false
      - REDIS_URL=redis
      - REDIS_DEFAULT_DATABASE=0
      - IDENTITY_PROVIDER_URL=https://marcelmichau.eu.auth0.com/
    ports:
      - "5000:80"
      - "5001:443"
    volumes:
      - ~/.aspnet/https:/root/.aspnet/https:ro
      - ~/.microsoft/userSecrets:/root/.microsoft/usersecrets:ro

  fake-survey-generator-worker:
    environment:
      - ConnectionStrings__SurveyContext=Server=sql-server;Database=FakeSurveyGenerator;user id=SA;pwd=<YourStrong!Passw0rd>;Encrypt=false
      - REDIS_PASSWORD=testing
      - REDIS_SSL=false
      - REDIS_URL=redis
      - REDIS_DEFAULT_DATABASE=0

  sql-server:
    ports:
      - "1433:1433"

  redis:
    ports:
      - "6379:6379"
