apiVersion: skaffold/v2beta13
kind: Config
build:
  artifacts:
    - image: marcelmichau/fakesurveygeneratorui
      context: .
      docker:
        dockerfile: src/client/ui/Dockerfile
    - image: marcelmichau/fakesurveygeneratorapi
      context: .
      docker:
        dockerfile: src/server/FakeSurveyGenerator.API/Dockerfile
  tagPolicy:
    sha256: {}
deploy:
  helm:
    releases:
      - name: fake-survey-generator-ui
        chartPath: ./charts/fake-survey-generator-ui
        artifactOverrides:
          image: marcelmichau/fakesurveygeneratorui
        namespace: default
        imageStrategy:
          helm: {}
      - name: fake-survey-generator-api
        chartPath: ./charts/fake-survey-generator-api
        valuesFiles:
          - skaffold-overrides/fake-survey-generator-api/local-values.yaml
        artifactOverrides:
          image: marcelmichau/fakesurveygeneratorapi
        namespace: default
        imageStrategy:
          helm: {}
      - name: sql-server
        chartPath: ./charts/sql-server
        namespace: default
        imageStrategy:
          helm: {}
      - name: redis
        chartPath: ./charts/redis
        namespace: default
        imageStrategy:
          helm: {}
