import { execFileSync } from "node:child_process";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import openapiTS, { astToString } from "openapi-typescript";

const root = resolve(dirname(fileURLToPath(import.meta.url)), "../..");
const project = resolve(root, "src/server/FakeSurveyGenerator.Api/FakeSurveyGenerator.Api.csproj");
const documents = resolve(root, "src/server/FakeSurveyGenerator.Api/obj/contracts");
const output = resolve(root, "src/client/ui/src/api/generated.d.ts");

execFileSync("dotnet", ["build", project, "--no-incremental",
  "-p:OpenApiGenerateDocuments=true", `-p:OpenApiDocumentsDirectory=${documents}`],
  { cwd: root, stdio: "inherit" });

const schema = JSON.parse(readFileSync(resolve(documents, "api.json"), "utf8"));
const generated = "// Generated by npm run generate:api. Do not edit manually.\n" +
  astToString(await openapiTS(schema));
if (process.argv.includes("--check")) {
  if (readFileSync(output, "utf8").replaceAll("\r\n", "\n") !== generated.replaceAll("\r\n", "\n")) {
    throw new Error("API contracts are out of date. Run npm run generate:api and commit the result.");
  }
  console.log("API contracts match the server.");
} else {
  mkdirSync(dirname(output), { recursive: true });
  writeFileSync(output, generated);
  console.log(`Generated ${output}`);
}
