trigger:
  batch: true
  branches:
    include:
      - main
  paths:
    include:
      - .azdo/*
      - src/server/*
      - src/client/frontend/*
      - infra/*

pr:
  branches:
    include:
      - main
      - feat/*
      - fix/*
      - chore/*
      - refactor/*
  paths:
    include:
      - .azdo/*
      - src/server/*
      - src/client/frontend/*
      - infra/*

parameters:
  - name: runAcceptanceTests
    displayName: "Enable Running Acceptance Tests"
    default: false
    type: boolean

variables:
  isMain: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  azureSubscriptionId: $(AZURE_SUBSCRIPTION_ID)
  azureEnvName: "dev"
  azureResourceGroup: rg-fake-survey-generator
  azureResourceManagerConnection: "Azure Service Connection"
  azureLocation: "South Africa North"
  apiActiveLabel: "blue"
  apiPromotePreview: "false"
  uiActiveLabel: "blue"
  uiPromotePreview: "false"
  NUGET_PACKAGES: $(Pipeline.Workspace)/.nuget/packages

stages:
  - stage: BuildTestApi
    displayName: "Build + Test API"
    jobs:
      - job: VersionSetup
        displayName: "Set Version Tags"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            inputs:
              command: custom
              custom: tool
              arguments: install --tool-path ./src/server nbgv --version 3.9.50
            displayName: Install NBGV tool

          - script: ./nbgv cloud -a
            workingDirectory: src/server
            displayName: Set Build Number & Version Variables

          - script: |
              echo "##vso[task.setvariable variable=VersionTag;isOutput=true]$(NBGV_SemVer1)"
            name: "SetVersionTag"
            displayName: "Set SemVer Version Tag from NBGV"

      - job: Build
        displayName: "Build + Test"
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
              projects: "FakeSurveyGenerator.slnx"
            displayName: "Build Solution"

          - task: DotNetCoreCLI@2
            inputs:
              command: "test"
              publishTestResults: true
              arguments: '--no-build --coverage --treenode-filter "/(*Tests*)&(!*Acceptance*)/*/*/*" --ignore-exit-code 8'
            displayName: "Run Unit + Integration Tests"

          - script: |
              dotnet tool restore
              dotnet dotnet-ef migrations script -o DbMigrationScript.sql -i
            workingDirectory: src/server/FakeSurveyGenerator.Application
            displayName: "Create Database Migration Script"

          - task: PublishPipelineArtifact@1
            inputs:
              targetPath: "src/server/FakeSurveyGenerator.Application/DbMigrationScript.sql"
              artifact: "DbMigrationScript"
            displayName: "Publish Database Migration Script"

      - job: AcceptanceTests
        displayName: "Run Acceptance (E2E) Tests"
        condition: ${{ eq(parameters.runAcceptanceTests, true) }} # .NET Aspire Tests hang in the pipeline so this is here until it is fixed
        pool:
          vmImage: "ubuntu-latest"
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              useGlobalJson: true

          - task: DotNetCoreCLI@2
            inputs:
              command: "build"
              projects: "FakeSurveyGenerator.slnx"
            displayName: "Build Solution"

          - script: |
              wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
            displayName: "Install Dapr CLI"

          - script: |
              dapr init
            displayName: "Dapr Init"

          - task: PowerShell@2
            inputs:
              filePath: "src/server/FakeSurveyGenerator.Acceptance.Tests/bin/Debug/net10.0/playwright.ps1"
              arguments: "install --with-deps"
            displayName: "Download Playwright Browsers"

          # https://github.com/dotnet/aspire/issues/13612
          - script: |
              dotnet dev-certs https --trust
            displayName: "Trust .NET Dev Certs"

          - task: DotNetCoreCLI@2
            inputs:
              command: "test"
              publishTestResults: true
              arguments: '--no-build --coverage --treenode-filter "/(*Acceptance.Tests*)/*/*/*" --ignore-exit-code 8'
            displayName: "Run Acceptance Tests"

  - stage: BuildTestUI
    displayName: "Build + Test UI"
    dependsOn: []
    jobs:
      - job: BuildAndTest
        displayName: "Build + Test"
        pool:
          vmImage: "ubuntu-latest"
        variables:
          projectName: fake-survey-generator-ui
          imageRepository: "$(registryName).azurecr.io/$(projectName)"
        steps:
          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              useGlobalJson: true

          - task: NodeTool@0
            displayName: "Install Node.js"
            inputs:
              versionSpec: "25.x"

          - task: DotNetCoreCLI@2
            displayName: Install NBGV tool
            inputs:
              command: custom
              custom: tool
              arguments: install --tool-path ./src/client/frontend nbgv --version 3.9.50

          - script: ./nbgv cloud -a
            workingDirectory: src/client/frontend
            displayName: Set Build Number & Version Variables

          - task: Npm@1
            displayName: "Install Frontend Dependencies"
            inputs:
              command: "install"
              workingDir: "src/client/frontend"

          - task: Npm@1
            displayName: "Run Frontend Unit Tests"
            inputs:
              command: "custom"
              workingDir: "src/client/frontend"
              customCommand: "test -- --run --reporter=junit --reporter=default --outputFile.junit=./test-results/junit.xml"

          - task: PublishTestResults@2
            displayName: "Publish Frontend Test Results"
            inputs:
              testResultsFormat: "JUnit"
              testResultsFiles: "src/client/frontend/test-results/junit.xml"
              failTaskOnFailedTests: true
            condition: succeededOrFailed()

          - script: |
              echo "##vso[task.setvariable variable=VersionTag;isOutput=true]$(NBGV_SemVer1)"
            name: "SetVersionTag"
            displayName: "Set SemVer Version Tag from NBGV"

  - stage: App_Deployment
    displayName: "Deploy App"
    condition: and(succeeded(), eq(variables.isMain, true))
    dependsOn:
      - BuildTestApi
      - BuildTestUI
    jobs:
      - job: Deploy
        displayName: "Provision Infra + Deploy App"
        pool:
          vmImage: "ubuntu-latest"
        variables:
          apiSemVerVersionTag: $[stageDependencies.BuildTestApi.VersionSetup.outputs['SetVersionTag.VersionTag']]
          uiSemVerVersionTag: $[stageDependencies.BuildTestUI.BuildAndTest.outputs['SetVersionTag.VersionTag']]
        steps:
          - task: setup-azd@1
            displayName: Install azd

          - pwsh: |
              azd config set auth.useAzCliAuth "true"
              azd config set alpha.deployment.stacks on
            displayName: Configure AZD

          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              useGlobalJson: true

          - task: AzureCLI@2
            displayName: Provision Infrastructure
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                azd provision --no-prompt
            env:
              AZURE_SUBSCRIPTION_ID: $(azureSubscriptionId)
              AZURE_ENV_NAME: $(azureEnvName)
              AZURE_LOCATION: $(azureLocation)
              AZURE_RESOURCE_GROUP: $(azureResourceGroup)

          - task: AzureCLI@2
            displayName: Deploy Application (Preview)
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                azd deploy --no-prompt
            env:
              AZURE_SUBSCRIPTION_ID: $(azureSubscriptionId)
              AZURE_ENV_NAME: $(azureEnvName)
              AZURE_LOCATION: $(azureLocation)
              AZURE_RESOURCE_GROUP: $(azureResourceGroup)
              UI_VERSION: $(uiSemVerVersionTag)
              API_VERSION: $(apiSemVerVersionTag)
              UI_ACTIVE_LABEL: $(uiActiveLabel)
              UI_PROMOTE_PREVIEW: "false"
              API_ACTIVE_LABEL: $(apiActiveLabel)
              API_PROMOTE_PREVIEW: "false"
              VITE_APP_VERSION: $(uiSemVerVersionTag)

          - task: AzureCLI@2
            displayName: Validate Preview API + UI URLs
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                set -euo pipefail

                API_APP_NAME=$(azd env get-values | sed -n 's/^SERVICE_API_NAME="\(.*\)"/\1/p')
                UI_APP_NAME=$(azd env get-values | sed -n 's/^SERVICE_UI_NAME="\(.*\)"/\1/p')

                if [[ -z "${API_APP_NAME}" || -z "${UI_APP_NAME}" ]]; then
                  echo "Unable to resolve SERVICE_API_NAME or SERVICE_UI_NAME from azd environment."
                  exit 1
                fi

                API_HOST=$(az containerapp show --resource-group "${AZURE_RESOURCE_GROUP}" --name "${API_APP_NAME}" --query properties.latestRevisionFqdn -o tsv)
                UI_HOST=$(az containerapp show --resource-group "${AZURE_RESOURCE_GROUP}" --name "${UI_APP_NAME}" --query properties.latestRevisionFqdn -o tsv)

                API_URL="https://${API_HOST}/health/ready"
                UI_URL="https://${UI_HOST}"

                echo "Validating API URL: ${API_URL}"
                echo "Validating UI URL: ${UI_URL}"

                for i in $(seq 1 20); do
                  API_STATUS=$(curl -k -sS -o /dev/null -w "%{http_code}" "${API_URL}" || true)
                  UI_STATUS=$(curl -k -sS -o /dev/null -w "%{http_code}" "${UI_URL}" || true)

                  if [[ "${API_STATUS}" == "200" && "${UI_STATUS}" == "200" ]]; then
                    echo "Preview validation succeeded (API=${API_STATUS}, UI=${UI_STATUS})."
                    exit 0
                  fi

                  echo "Attempt ${i}/20: API=${API_STATUS}, UI=${UI_STATUS}. Retrying in 15s..."
                  sleep 15
                done

                echo "Preview validation failed after retries."
                exit 1
            env:
              AZURE_SUBSCRIPTION_ID: $(azureSubscriptionId)
              AZURE_ENV_NAME: $(azureEnvName)
              AZURE_LOCATION: $(azureLocation)
              AZURE_RESOURCE_GROUP: $(azureResourceGroup)

          - task: AzureCLI@2
            displayName: Promote Preview to Production Label
            inputs:
              azureSubscription: $(azureResourceManagerConnection)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                azd deploy --no-prompt
            env:
              AZURE_SUBSCRIPTION_ID: $(azureSubscriptionId)
              AZURE_ENV_NAME: $(azureEnvName)
              AZURE_LOCATION: $(azureLocation)
              AZURE_RESOURCE_GROUP: $(azureResourceGroup)
              UI_VERSION: $(uiSemVerVersionTag)
              API_VERSION: $(apiSemVerVersionTag)
              UI_ACTIVE_LABEL: $(uiActiveLabel)
              UI_PROMOTE_PREVIEW: "true"
              API_ACTIVE_LABEL: $(apiActiveLabel)
              API_PROMOTE_PREVIEW: "true"
              VITE_APP_VERSION: $(uiSemVerVersionTag)

  - stage: Database_Deployment
    condition: and(succeeded(), eq(variables.isMain, true))
    dependsOn:
      - App_Deployment
    displayName: "Deploy Database"
    jobs:
      - deployment: Deployment_Job
        displayName: Deploy Database Migration Script
        pool:
          vmImage: "windows-latest"
        variables:
          sqlServerName: "sql-fake-survey-generator.database.windows.net"
          sqlDatabaseName: sqldb-fake-survey-generator
        environment: "azure-sql"
        strategy:
          runOnce:
            deploy:
              steps:
                - task: SqlAzureDacpacDeployment@1
                  displayName: "Execute SQL Migration Script"
                  inputs:
                    azureSubscription: $(azureResourceManagerConnection)
                    AuthenticationType: "servicePrincipal"
                    ServerName: "$(sqlServerName)"
                    DatabaseName: "$(sqlDatabaseName)"
                    deployType: SqlTask
                    SqlFile: "$(Pipeline.Workspace)/DbMigrationScript/DbMigrationScript.sql"
