replicaCount: 1

image:
  repository: marcelmichau/fakesurveygeneratorui
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Content-Security-Policy default-src 'none'; script-src 'self' 'unsafe-inline'; script-src-elem 'self' 'unsafe-inline' data:; style-src 'self' 'unsafe-inline'; connect-src 'self' https://marcelmichau.eu.auth0.com; manifest-src 'self'; font-src 'self' data:; img-src 'self' data:; object-src 'none'; block-all-mixed-content; frame-ancestors 'none'; base-uri 'none'; form-action 'none';";
      more_set_headers "X-Frame-Options DENY";
      more_set_headers "X-XSS-Protection 1; mode=block";
      more_set_headers "X-Content-Type-Options nosniff";
      more_set_headers "Referrer-Policy strict-origin-when-cross-origin";
      more_set_headers "Permissions-Policy camera=(), microphone=(), geolocation=(), accelerometer=(), gyroscope=(), autoplay=()";
      more_set_headers "Cross-Origin-Embedder-Policy require-corp";
      more_set_headers "Cross-Origin-Opener-Policy same-origin";
      more_set_headers "Cross-Origin-Resource-Policy same-origin";
  hosts:
    - host: k8s.local
      paths:
        - /

  tls:
    - secretName: k8s-local-tls-secret
      hosts:
        - k8s.local

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
