// Generated by npm run generate:api. Do not edit manually.
export interface paths {
    "/api/admin/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns API version information */
        get: operations["GetVersionInformation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/ping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Returns a 200 OK Result. Used for testing network latency and as a sanity check */
        get: operations["Ping"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/secret-test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a test secret from Dapr Secret Store. Uses local file in Development & Azure Key Vault in Production */
        get: operations["SecretTest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/survey/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a specific Survey */
        get: operations["GetSurvey"];
        put?: never;
        post?: never;
        /** Deletes a Survey owned by the current user */
        delete: operations["DeleteSurvey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/survey/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves all Surveys created by the current user */
        get: operations["GetUserSurveys"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/survey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Creates a new Survey */
        post: operations["CreateSurvey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/survey/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyzes a Survey before creation */
        post: operations["AnalyzeSurvey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Retrieves a specific User */
        get: operations["GetUser"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/isRegistered": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Checks whether or not a User with a specific UserId is already registered in the system */
        get: operations["IsRegistered"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/user/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Registers a new User, using the information from the access token */
        post: operations["Register"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AnalyzeSurveyCommand: {
            surveyTopic: string;
            respondentType: string;
            surveyOptions: components["schemas"]["SurveyOptionDto"][];
        };
        ApiVersionModel: {
            assemblyVersion: string;
            assemblyFileVersion: string;
            assemblyInformationalVersion: string;
            assemblyName: string;
            assemblyTitle: string;
            assemblyConfiguration: string;
            rootNamespace: string;
            /** Format: date-time */
            gitCommitDate: string;
            gitCommitId: string;
        };
        CreateSurveyCommand: {
            surveyTopic: string;
            /** Format: int32 */
            numberOfRespondents: number;
            respondentType: string;
            surveyOptions: components["schemas"]["SurveyOptionDto"][];
        };
        ProblemDetails: {
            type?: null | string;
            title?: null | string;
            /** Format: int32 */
            status?: null | number;
            detail?: null | string;
            instance?: null | string;
        };
        SurveyAnalysisModel: {
            responseShape: string;
            /** Format: double */
            responseShapeConfidence: number;
            /** Format: double */
            leadingProbability: number;
            /** Format: double */
            multipleChoiceProbability: number;
            /** Format: double */
            coverageProbability: number;
            warnings: components["schemas"]["SurveyAnalysisWarningModel"][];
        };
        SurveyAnalysisWarningModel: {
            code: string;
            title: string;
            message: string;
            /** Format: double */
            probability: number;
        };
        SurveyModel: {
            /** Format: int32 */
            id: number;
            /** Format: int32 */
            ownerId: number;
            ownerExternalUserId: string;
            topic: string;
            respondentType: string;
            /** Format: int32 */
            numberOfRespondents: number;
            isRigged: boolean;
            options: components["schemas"]["SurveyOptionModel"][];
            createdBy: null | string;
            /** Format: date-time */
            createdOn: string;
            modifiedBy: null | string;
            /** Format: date-time */
            modifiedOn: null | string;
        };
        SurveyOptionDto: {
            optionText: string;
            /** Format: int32 */
            preferredNumberOfVotes?: number;
        };
        SurveyOptionModel: {
            optionText: string;
            /** Format: int32 */
            numberOfVotes: number;
            /** Format: int32 */
            preferredNumberOfVotes: number;
        };
        UserModel: {
            /** Format: int32 */
            id: number;
            displayName: string;
            emailAddress: string;
            externalUserId: string;
            createdBy: null | string;
            /** Format: date-time */
            createdOn: string;
            modifiedBy: null | string;
            /** Format: date-time */
            modifiedOn: null | string;
        };
        UserRegistrationStatusModel: {
            isUserRegistered?: boolean;
        };
        UserSurveyModel: {
            /** Format: int32 */
            id: number;
            topic: string;
            respondentType: string;
            /** Format: int32 */
            numberOfRespondents: number;
            /** Format: int32 */
            numberOfOptions: number;
            winningOption: string;
            /** Format: int32 */
            winningOptionNumberOfVotes: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    GetVersionInformation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiVersionModel"];
                };
            };
        };
    };
    Ping: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    SecretTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetSurvey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Primary key of the Survey */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    DeleteSurvey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Primary key of the Survey */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    GetUserSurveys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserSurveyModel"][];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    CreateSurvey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSurveyCommand"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
        };
    };
    AnalyzeSurvey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalyzeSurveyCommand"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SurveyAnalysisModel"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string[];
                    };
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/problem+json": components["schemas"]["ProblemDetails"];
                };
            };
        };
    };
    GetUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Primary key of the User */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    IsRegistered: {
        parameters: {
            query: {
                /** @description The external user identifier */
                userId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserRegistrationStatusModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    Register: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserModel"];
                };
            };
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserModel"];
                };
            };
            /** @description Unauthorized */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
